max_iters: 10000
batch_size: 64
learning_rate: 3e-4
eval_iters: 200
eval_interval: 500
checkpoint_interval: 1000
checkpoint_dir: "checkpoints"
resume_path: null 
use_wandb: True
project_name: "nano_gpt"
run_name: "gpt_v1"